apiVersion: v1
kind: Secret
metadata:
  name: academic-registration-secrets
  namespace: academic-registration
  labels:
    app.kubernetes.io/name: academic-registration
type: Opaque
stringData:
  sqlserver-sa-password: AcademicReg!2026
  email-username: ""
  email-password: ""
