apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data
  namespace: academic-registration
  labels:
    app.kubernetes.io/name: academic-registration
    app.kubernetes.io/component: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: academic-registration
  labels:
    app.kubernetes.io/name: academic-registration
    app.kubernetes.io/component: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
