apiVersion: v1
kind: Secret
metadata:
  name: oci-managed-kafka-client
  namespace: kafka-poc
type: Opaque
stringData:
  KAFKA_BOOTSTRAP_SERVERS: "<terraform-output-bootstrap_servers>"
  KAFKA_USERNAME: "<sasl-scram-username>"
  KAFKA_PASSWORD: "<sasl-scram-password>"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
  # Optional for Java clients if your runtime does not trust the broker CA by default.
  KAFKA_SSL_TRUSTSTORE_LOCATION: ""
  KAFKA_SSL_TRUSTSTORE_PASSWORD: ""
