output "kafka_cluster_id" {
  description = "Managed Kafka cluster OCID."
  value       = oci_managed_kafka_kafka_cluster.poc.id
}

output "kafka_cluster_state" {
  description = "Managed Kafka cluster lifecycle state."
  value       = oci_managed_kafka_kafka_cluster.poc.state
}

output "kafka_bootstrap_urls" {
  description = "All bootstrap URLs exposed by the cluster."
  value       = oci_managed_kafka_kafka_cluster.poc.kafka_bootstrap_urls
}

output "bootstrap_servers" {
  description = "Comma-separated bootstrap servers for Kafka clients."
  value       = join(",", [for endpoint in oci_managed_kafka_kafka_cluster.poc.kafka_bootstrap_urls : endpoint.url])
}

output "cluster_config_id" {
  description = "Kafka cluster config OCID."
  value       = oci_managed_kafka_kafka_cluster_config.poc.id
}

output "cluster_config_version" {
  description = "Kafka cluster config version used by the cluster."
  value       = oci_managed_kafka_kafka_cluster_config.poc.latest_config[0].version_number
}

output "sasl_scram_secret_id" {
  description = "Vault secret OCID associated with SASL/SCRAM when provided or generated by the service."
  value       = local.sasl_scram_secret_id
}

output "sasl_scram_vault_id" {
  description = "Vault OCID created by this PoC, when create_sasl_scram_secret is true."
  value       = try(oci_kms_vault.kafka_poc[0].id, null)
}

output "sasl_scram_key_id" {
  description = "Vault key OCID created by this PoC, when create_sasl_scram_secret is true."
  value       = try(oci_kms_key.kafka_poc[0].id, null)
}
